"""
Accumulator ("ACCU") contract mechanics and a historical-data simulator.

How Accumulators work (per Deriv's public documentation, verify current
numbers at https://developers.deriv.com/docs/accumulator-options/ before
relying on this):
  - You choose a growth rate g in {0.01, 0.02, 0.03, 0.04, 0.05}.
  - Deriv computes a symmetric barrier around the spot price at entry, and
    re-centers it every tick. The exact barrier width for a given g depends
    on the underlying's volatility model and is NOT published as a simple
    formula -- always pull it from a live `proposal` call rather than
    hardcoding it.
  - As long as price stays within the barrier, your stake compounds:
        value_after_n_ticks = stake * (1 + g) ** n
  - If price touches/breaches the barrier on a tick, the contract is
    "knocked out" and you lose the stake entirely (no partial refund).
  - Contracts auto-close at 230 ticks or a $10,000 payout cap, whichever
    comes first (Deriv-stated limits as of the docs above -- reconfirm,
    these can change).

This module lets you:
  1. Compute payouts/knockout math (`payout_after_ticks`, `max_ticks_for_cap`)
  2. Backtest "how would a fixed-duration or take-profit accumulator have
     performed" against historical tick data you already pulled via
     DerivClient.tick_history(...).

This is NOT a prediction tool. Synthetic indices are generated by a
published pseudo-random volatility model; historical run lengths describe
what already happened, they do not forecast what a *new* contract opened
right now will do.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

from analysis import no_touch_run_lengths

PAYOUT_CAP = 10_000.0
MAX_TICKS = 230


def payout_after_ticks(stake: float, growth_rate: float, ticks_survived: int) -> float:
    value = stake * (1 + growth_rate) ** ticks_survived
    return min(value, PAYOUT_CAP)


def max_ticks_for_cap(stake: float, growth_rate: float) -> int:
    """How many surviving ticks it'd take to hit the $10,000 payout cap."""
    import math
    if stake <= 0 or growth_rate <= 0:
        return MAX_TICKS
    n = math.log(PAYOUT_CAP / stake) / math.log(1 + growth_rate)
    return min(MAX_TICKS, max(0, int(n) + 1))


@dataclass
class BacktestResult:
    trials: int
    stake: float
    growth_rate: float
    target_ticks: int
    wins: int
    losses: int
    win_rate: float
    avg_payout: float
    avg_pnl: float
    total_pnl: float

    def summary(self) -> str:
        return (
            f"Backtest: {self.trials} trials, stake={self.stake}, growth_rate={self.growth_rate:.0%}, "
            f"target={self.target_ticks} ticks\n"
            f"  wins={self.wins} losses={self.losses} win_rate={self.win_rate:.2%}\n"
            f"  avg_payout={self.avg_payout:.4f} avg_pnl={self.avg_pnl:+.4f} total_pnl={self.total_pnl:+.4f}"
        )


def backtest_fixed_target(
    prices: Sequence[float],
    barrier_pct: float,
    stake: float,
    growth_rate: float,
    target_ticks: int,
) -> BacktestResult:
    """Simulates: 'open an accumulator at every possible historical tick,
    hold until `target_ticks` survived (take profit there) or knockout,
    whichever comes first.' barrier_pct must come from a live proposal
    (see fetch_barrier_pct below) for the growth_rate you're testing --
    do not guess it.
    """
    run_lengths = no_touch_run_lengths(prices, barrier_pct)
    wins = losses = 0
    total_pnl = 0.0
    total_payout = 0.0

    for run in run_lengths:
        if run >= target_ticks:
            payout = payout_after_ticks(stake, growth_rate, target_ticks)
            pnl = payout - stake
            wins += 1
        else:
            payout = 0.0
            pnl = -stake
            losses += 1
        total_pnl += pnl
        total_payout += payout

    trials = len(run_lengths)
    return BacktestResult(
        trials=trials,
        stake=stake,
        growth_rate=growth_rate,
        target_ticks=target_ticks,
        wins=wins,
        losses=losses,
        win_rate=wins / trials if trials else 0.0,
        avg_payout=total_payout / trials if trials else 0.0,
        avg_pnl=total_pnl / trials if trials else 0.0,
        total_pnl=total_pnl,
    )


async def fetch_barrier_pct(client, symbol: str, stake: float, growth_rate: float) -> float:
    """Pulls a live proposal from Deriv and derives the actual barrier width
    (as a fraction of spot) that Deriv is currently quoting for this
    symbol/growth_rate. This is the *real* number to feed into
    backtest_fixed_target -- far better than guessing.
    """
    resp = await client.accumulator_proposal(symbol=symbol, stake=stake, growth_rate=growth_rate)
    proposal = resp.get("proposal", {})
    spot = proposal.get("spot")
    high = (proposal.get("contract_details") or {}).get("high_barrier") or proposal.get("high_barrier")
    low = (proposal.get("contract_details") or {}).get("low_barrier") or proposal.get("low_barrier")
    if spot and high and low:
        return float((float(high) - float(low)) / 2 / float(spot))
    raise ValueError(
        f"Couldn't find barrier fields in proposal response, got keys: {list(proposal.keys())}. "
        "The response schema may differ from what this code expects -- print(resp) and adjust."
    )
