"""
Statistical analysis of tick/price data for Deriv synthetic indices.

Everything here is descriptive statistics on historical data. None of it
predicts future price movement -- synthetic indices are generated by a
random process, and past tick patterns do not change future odds. Treat
this as a way to *understand* an instrument's behaviour, not a signal
generator.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

import numpy as np


@dataclass
class TickStats:
    symbol: str
    n: int
    mean: float
    std: float
    min_: float
    max_: float
    pct_changes_mean: float
    pct_changes_std: float
    up_ticks: int
    down_ticks: int
    flat_ticks: int
    longest_up_streak: int
    longest_down_streak: int
    current_streak: int  # positive = up streak, negative = down streak

    def summary(self) -> str:
        return (
            f"{self.symbol}: n={self.n} mean={self.mean:.5f} std={self.std:.5f} "
            f"range=[{self.min_:.5f}, {self.max_:.5f}]\n"
            f"  tick moves: up={self.up_ticks} down={self.down_ticks} flat={self.flat_ticks}\n"
            f"  pct-change: mean={self.pct_changes_mean:.6%} std={self.pct_changes_std:.6%}\n"
            f"  longest up streak={self.longest_up_streak}  "
            f"longest down streak={self.longest_down_streak}  "
            f"current streak={self.current_streak}"
        )


def compute_tick_stats(symbol: str, prices: Sequence[float]) -> TickStats:
    arr = np.asarray(prices, dtype=float)
    if len(arr) < 2:
        raise ValueError("Need at least 2 prices to compute stats")

    diffs = np.diff(arr)
    pct = diffs / arr[:-1]

    up = int(np.sum(diffs > 0))
    down = int(np.sum(diffs < 0))
    flat = int(np.sum(diffs == 0))

    longest_up = longest_down = cur = 0
    best_up = best_down = 0
    for d in diffs:
        if d > 0:
            cur = cur + 1 if cur > 0 else 1
        elif d < 0:
            cur = cur - 1 if cur < 0 else -1
        else:
            cur = 0
        best_up = max(best_up, cur)
        best_down = min(best_down, cur)
    longest_up = best_up
    longest_down = -best_down

    return TickStats(
        symbol=symbol,
        n=len(arr),
        mean=float(np.mean(arr)),
        std=float(np.std(arr)),
        min_=float(np.min(arr)),
        max_=float(np.max(arr)),
        pct_changes_mean=float(np.mean(pct)),
        pct_changes_std=float(np.std(pct)),
        up_ticks=up,
        down_ticks=down,
        flat_ticks=flat,
        longest_up_streak=longest_up,
        longest_down_streak=longest_down,
        current_streak=cur,
    )


def realized_volatility(prices: Sequence[float], annualize_ticks_per_year: int | None = None) -> float:
    """Std dev of log returns. If annualize_ticks_per_year is given, scales to an
    annualized figure (rough, since synthetic-index tick cadence isn't fixed
    to real calendar time in a simple way -- treat as approximate)."""
    arr = np.asarray(prices, dtype=float)
    log_ret = np.diff(np.log(arr))
    vol = float(np.std(log_ret))
    if annualize_ticks_per_year:
        vol *= np.sqrt(annualize_ticks_per_year)
    return vol


def rolling_volatility(prices: Sequence[float], window: int = 50) -> np.ndarray:
    arr = np.asarray(prices, dtype=float)
    log_ret = np.diff(np.log(arr))
    if len(log_ret) < window:
        return np.array([])
    out = np.array(
        [np.std(log_ret[i - window : i]) for i in range(window, len(log_ret) + 1)]
    )
    return out


def no_touch_run_lengths(prices: Sequence[float], barrier_pct: float) -> list[int]:
    """For a symmetric barrier of +/- barrier_pct around each tick's entry price
    (the same mechanism accumulators use), compute how many consecutive ticks
    price stays within the range before breaching it, for every possible
    starting tick. Useful for accumulator_options.simulate_accumulator_run.
    """
    arr = np.asarray(prices, dtype=float)
    run_lengths = []
    n = len(arr)
    for start in range(n - 1):
        entry = arr[start]
        upper = entry * (1 + barrier_pct)
        lower = entry * (1 - barrier_pct)
        run = 0
        for j in range(start + 1, n):
            if lower <= arr[j] <= upper:
                run += 1
                entry = arr[j]  # range recenters each tick, as Deriv accumulators do
                upper = entry * (1 + barrier_pct)
                lower = entry * (1 - barrier_pct)
            else:
                break
        run_lengths.append(run)
    return run_lengths
