"""
Deriv "Matches" Digit Bot — predicts digit 9, R_100
=====================================================

IMPORTANT HONESTY NOTE (please actually read this):
On Deriv, the last digit of each tick on a synthetic index is generated by
a random process and is (very close to) uniformly distributed 0-9,
independent of prior digits. That means:
  - The true win probability for "Matches" on any single digit is ~10%
    per trade, regardless of any filter, indicator, or pattern.
  - The payout odds are set so the platform keeps a statistical edge.
  - No staking method (martingale, fixed stake, anti-martingale, etc.)
    changes the underlying win rate — staking only changes how fast you
    can win or lose your account balance.
This bot uses a FIXED stake (no martingale) as you requested — this is
the safer choice because it removes the risk of an exponentially growing
bet size wiping out your account after a losing streak. It does NOT make
the strategy profitable in expectation. Treat this as a tool for
disciplined, capped-risk experimentation — not a guaranteed income system.

SETUP
-----
1. pip install python-deriv-api websockets
   (or: pip install websockets   -- this script uses raw websockets so you
    don't strictly need python-deriv-api)
2. Get an API token: https://app.deriv.com/account/api-token
   Give it "Trade" scope.
3. Fill in CONFIG below.
4. Run: python deriv_matches_bot.py

Start on a DEMO account first. Seriously.
"""

import asyncio
import json
import websockets
from collections import deque

# ======================= CONFIG =======================
API_TOKEN   = "YOUR_DERIV_API_TOKEN_HERE"   # <-- put your token here
APP_ID      = "1089"                        # public demo app_id, fine to keep
SYMBOL      = "R_100"                       # Volatility 100 Index
PREDICTION_DIGIT = 9                        # digit to bet will "Match"
STAKE       = 1.00                          # <-- fixed stake, YOU set this. No martingale.
DURATION    = 1                             # number of ticks
CURRENCY    = "USD"

# Risk controls (recommended — not optional in spirit, only in code)
MAX_TRADES_PER_SESSION = 50
DAILY_STOP_LOSS   = 20.00     # stop trading if total P/L drops below -this
DAILY_TAKE_PROFIT = 20.00     # stop trading if total P/L rises above +this

# Optional "cold digit" filter — only trade digit 9 if it hasn't shown up
# in the last N ticks. This does NOT change true probability, it just
# changes *when* you place fixed-probability bets. Set ENABLE_FILTER=False
# to trade on every tick instead.
ENABLE_FILTER = True
COLD_STREAK_LENGTH = 15   # only bet if digit 9 absent from last N ticks
# ========================================================

WS_URL = f"wss://ws.derivws.com/websockets/v3?app_id={APP_ID}"


class MatchesBot:
    def __init__(self):
        self.ws = None
        self.req_id = 0
        self.trades_taken = 0
        self.total_pnl = 0.0
        self.wins = 0
        self.losses = 0
        self.recent_digits = deque(maxlen=COLD_STREAK_LENGTH)
        self.stop_flag = False

    def next_id(self):
        self.req_id += 1
        return self.req_id

    async def send(self, payload):
        payload["req_id"] = self.next_id()
        await self.ws.send(json.dumps(payload))

    async def authorize(self):
        await self.send({"authorize": API_TOKEN})
        resp = await self.recv_matching("authorize")
        if resp.get("error"):
            raise RuntimeError(f"Authorization failed: {resp['error']['message']}")
        print(f"[OK] Authorized as {resp['authorize']['loginid']} "
              f"({resp['authorize']['currency']}, balance {resp['authorize']['balance']})")

    async def recv_matching(self, msg_type):
        # Reads messages until it finds the one matching msg_type
        while True:
            raw = await self.ws.recv()
            data = json.loads(raw)
            if data.get("msg_type") == msg_type:
                return data
            if data.get("error"):
                return data

    async def subscribe_ticks(self):
        await self.send({"ticks": SYMBOL, "subscribe": 1})
        print(f"[OK] Subscribed to ticks for {SYMBOL}")

    def last_digit_of(self, quote_str):
        # Deriv sends price as string with fixed decimals; last char is last digit
        return int(str(quote_str).replace(".", "")[-1])

    def should_trade(self):
        if not ENABLE_FILTER:
            return True
        if len(self.recent_digits) < COLD_STREAK_LENGTH:
            return False  # not enough history yet
        return PREDICTION_DIGIT not in self.recent_digits

    def risk_limits_hit(self):
        if self.trades_taken >= MAX_TRADES_PER_SESSION:
            print("[STOP] Max trades per session reached.")
            return True
        if self.total_pnl <= -abs(DAILY_STOP_LOSS):
            print("[STOP] Daily stop-loss hit.")
            return True
        if self.total_pnl >= abs(DAILY_TAKE_PROFIT):
            print("[STOP] Daily take-profit hit.")
            return True
        return False

    async def place_trade(self):
        proposal_req = {
            "buy": 1,
            "price": STAKE,
            "parameters": {
                "amount": STAKE,
                "basis": "stake",
                "contract_type": "DIGITMATCH",
                "currency": CURRENCY,
                "duration": DURATION,
                "duration_unit": "t",
                "symbol": SYMBOL,
                "barrier": str(PREDICTION_DIGIT),
            }
        }
        await self.send(proposal_req)
        resp = await self.recv_matching("buy")
        if resp.get("error"):
            print(f"[ERROR] Trade failed: {resp['error']['message']}")
            return
        contract_id = resp["buy"]["contract_id"]
        buy_price = resp["buy"]["buy_price"]
        self.trades_taken += 1
        print(f"[TRADE #{self.trades_taken}] Bought DIGITMATCH({PREDICTION_DIGIT}) "
              f"on {SYMBOL}, stake {STAKE}, contract_id={contract_id}")
        await self.track_contract(contract_id, buy_price)

    async def track_contract(self, contract_id, buy_price):
        await self.send({"proposal_open_contract": 1, "contract_id": contract_id, "subscribe": 1})
        while True:
            raw = await self.ws.recv()
            data = json.loads(raw)
            if data.get("msg_type") != "proposal_open_contract":
                continue
            poc = data.get("proposal_open_contract", {})
            if poc.get("contract_id") != contract_id:
                continue
            if poc.get("is_sold"):
                profit = float(poc.get("profit", 0))
                self.total_pnl += profit
                if profit > 0:
                    self.wins += 1
                    print(f"  -> WIN  | profit: {profit:+.2f} | session P/L: {self.total_pnl:+.2f}")
                else:
                    self.losses += 1
                    print(f"  -> LOSS | profit: {profit:+.2f} | session P/L: {self.total_pnl:+.2f}")
                break

    async def run(self):
        async with websockets.connect(WS_URL) as ws:
            self.ws = ws
            await self.authorize()
            await self.subscribe_ticks()

            while not self.stop_flag:
                raw = await self.ws.recv()
                data = json.loads(raw)

                if data.get("msg_type") == "tick":
                    quote = data["tick"]["quote"]
                    digit = self.last_digit_of(quote)
                    self.recent_digits.append(digit)

                    if self.risk_limits_hit():
                        self.stop_flag = True
                        break

                    if self.should_trade():
                        await self.place_trade()

            print("\n===== SESSION SUMMARY =====")
            print(f"Trades taken : {self.trades_taken}")
            print(f"Wins / Losses: {self.wins} / {self.losses}")
            if self.trades_taken:
                print(f"Win rate     : {self.wins/self.trades_taken*100:.1f}%")
            print(f"Total P/L    : {self.total_pnl:+.2f} {CURRENCY}")


if __name__ == "__main__":
    if API_TOKEN == "YOUR_DERIV_API_TOKEN_HERE":
        print("Please set your API_TOKEN in the CONFIG section before running.")
    else:
        try:
            asyncio.run(MatchesBot().run())
        except KeyboardInterrupt:
            print("\nStopped by user.")
